### ISSUE TITLE
Trouble Loading Extension in Chrome

### ISSUE THREAD

**Issue by vitaliyhayda** [olliethedev/gpt4-vision-chrome-extension#1]
I'm encountering an issue when attempting to load your extension in Chrome. Here's a step-by-step breakdown of what I did:

Step 1: I downloaded the repository in ZIP format.
Step 2: I opened Chrome, navigated to 'Manage Extensions,' and selected 'Load Unpacked' to install the extension manually.
Step 3: I tried using the 'Load Unpacked' feature with two different approaches: first, by selecting the entire extracted folder, and second, by choosing only the 'static' subfolder. Unfortunately, in both scenarios, the extension failed to load.

**Comment by olliethedev** [comment]
Hi @vitaliyhayda 

Sorry for the issue you encountered. I will update the README.md right now. But to run the extension in chrome you need to do the following steps:

1) Install dependencies:

```bash
npm install
```

2) Build the project:

```bash
npm run build
```

3) got to `chrome://extensions/` select `load unpacked` then select the `/dist` folder from the project.

**Comment by cameronking4** [comment]
I added .env and I get Submit to appear but nothing happens afterwards. Error is returned in console can't connect to localhost. I don't get the chat or tag experience or naviagtion just input area. Any resolve?
