### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by mukulpatnaik** [olliethedev/gpt4-vision-chrome-extension#2]
Hi,

Thanks for open sourcing this extension, it's a really cool idea. Unfortunately I cannot get it to work.

I've installed, built and loaded the unpacked extension but when I send a message, nothing happens. I've attached a screenshot of the console as well so you can see the errors. 

<img width="1512" alt="Screenshot 2023-11-13 at 9 27 24 AM" src="https://github.com/olliethedev/gpt4-vision-chrome-extension/assets/36257370/4be4b51f-cf15-4458-98b2-c22ceae5d934">

I think the `Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.` error implies that maybe the content.js has not loaded properly?

**Comment by olliethedev** [comment]
Hi @mukulpatnaik 

You need to refresh the page you are testing the extension on every time AFTER you load the unpacked extension. 

Its annoying but I think the extension scripts (content.js/background.js) are only injected once you refresh a page after installing the extension.

Hope this helps! 
Cheers!

**Comment by mukulpatnaik** [comment]
Thanks! That got it to work. 

Just curious, how did you get it to open a new tab and persist state in your demo on Twitter? When I try it, it loses state when it visits another website or opens another tab. Here's an example with trying to add an item to an Amazon cart.

https://github.com/olliethedev/gpt4-vision-chrome-extension/assets/36257370/25b4c6c9-1267-462e-8d86-0872cbe370a6

Here's an example of trying to like a post on Twitter:

https://github.com/olliethedev/gpt4-vision-chrome-extension/assets/36257370/ffddaa64-6947-45c5-8cf5-0e8b7be45d27

**Comment by olliethedev** [comment]
> Just curious, how did you get it to open a new tab and persist state in your demo on Twitter? When I try it, it loses state when it visits another website or opens another tab. Here's an example with trying to add an item to an Amazon cart.

With the magic of video editing. 😅 

You need to re-open the modal for the tool execution to continue. 
Quick search tells me you can perform long running executions from the `background.js` script. But that will require you to refactor the codebase.

**Comment by developer2013** [comment]
@olliethedev where i have to insert the API Key? I get this error: 

Uncaught Error: The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).

**Comment by olliethedev** [comment]
Hi @developer2013 
You need to add `.env` file to the root of the project directory. See `.env.example` for key name.

**Comment by developer2013** [comment]
> Hi @developer2013
> You need to add `.env` file to the root of the project directory. See `.env.example` for key name.

so you mean i have to create the file?

**Comment by olliethedev** [comment]
Correct

**Comment by developer2013** [comment]
> Correct

Can you give an example, it's not working :( do I have to start it with npm ? 
and the system can do all tasks i give him, and can work for me in the chrome browser?
